apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql_dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storeage: 10Gi
  storageClassName: standard-row

---

apiVersion: v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: abraaoleonardo/mysql:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306


---

apiVersion: v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 10
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: abraaoleonardo/php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80